apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brezgreha
resources:
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
  - counter/deployment.yaml
  - counter/service.yaml
  - counter/ingress.yaml
images:
  - name: brezgreha
    newName: rg.fr-par.scw.cloud/djnd/brezgreha
    newTag: 'dae4456256538c926ff44b0607a51470fce77a09'
  - name: counter
    newName: rg.fr-par.scw.cloud/djnd/counter
    newTag: 'dae4456256538c926ff44b0607a51470fce77a09'
