apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brezgreha
resources:
  - front/deployment.yaml
  - front/service.yaml
  - front/ingress.yaml
  - counter/deployment.yaml
  - counter/service.yaml
  - counter/ingress.yaml
images:
  - name: brezgreha
    newName: rg.fr-par.scw.cloud/djnd/brezgreha
    newTag: '0f45786190b3797a54081ce3f8ead61b8350c72a'
  - name: counter
    newName: rg.fr-par.scw.cloud/djnd/counter
    newTag: '0f45786190b3797a54081ce3f8ead61b8350c72a'
