apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glas-ljudstva
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
- name: counter
  newName: rg.fr-par.scw.cloud/djnd/counter
  newTag: 'latest'
